# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 74ae1bb1760c33e2c45fcbbaebdfb72ed6e4e4d559bee998e30dfe17ab096e0530aa8664d48060c397cb3841e3c04a647ba0d0f9824289214e2ce801ac52c74b

test:
  secret_key_base: f051b26e451bf3e11914a140804f4d437dada68ea2c64888f976c5f5ddfc41da8f8d637833d7b73f7a9335bd9078815f3272935117c2a06b261cd9843fd9942d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
